### ISSUE TITLE
how do you connect the python with web?

### ISSUE THREAD

**Issue by bakar6998** [dev-muhammad/Django-course#1]
Hi muhammad i saw your code and I am confused about your class and function which one u used in coding

**Comment by dev-muhammad** [comment]
@bakar6998 this repository is for offline course notes and some code examples. Maybe some code examples are not fully completed. 

>  how do you connect the python with web?

If you want to learn web apps with Django, I recommend you to start with this [tutorial](https://docs.djangoproject.com/en/4.2/intro/tutorial01/) from the django official documentation.

**Comment by bakar6998** [comment]
OK THANX MUHAMMAD
